[package]
name = "mutsuki-std-plugins"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mutsuki-plugin-io-browser-chromium = { path = "../../plugins/mutsuki-plugin-io-browser-chromium" }
mutsuki-plugin-io-http-client = { path = "../../plugins/mutsuki-plugin-io-http-client" }
mutsuki-plugin-image-render.workspace = true
mutsuki-plugin-resource-memory = { path = "../../plugins/mutsuki-plugin-resource-memory" }
mutsuki-plugin-resource-sqlite = { path = "../../plugins/mutsuki-plugin-resource-sqlite" }
mutsuki-runtime-contracts.workspace = true

[lints]
workspace = true
